### ISSUE TITLE
Containerize the application

### ISSUE THREAD

**Issue by bill-ahmed** [nikel-api/nikel#2]
Setup a basic docker stack to build and containerize Nikel images. Would make it much safer and easier to deploy on a number of platforms.

**Comment by bill-ahmed** [comment]
I believe there are some base images we can use via the default docker registry (for Go), although i'm a total noob when it comes to Go so i'll have to look into that.

**Comment by darenliang** [comment]
I think a good end goal is to be able to pull pre-built images off of a container registry service like [docker hub](https://hub.docker.com/).
