### ISSUE TITLE
Acorn API

### ISSUE THREAD

**Issue by OwaisSiddiqui** [nikel-api/nikel#9]
I was wondering if it's possible to have an Acorn API to access personal student course information by logging in through their UTORID.

**Comment by darenliang** [comment]
Hi Owais,

Implementing an Acorn API bridge was always under consideration but it was eventually ruled out for its security concerns.

The main concern is the ability to mutate course enrollments. It ends up being very complicated as the passwords must be stored raw (without salts and hashes). This might be outdated but the process of logging in should be similar to https://github.com/huchenlei/acorn-api-js/blob/master/src/BasicAcornAPI.ts#L40.

It's not to say it isn't possible, but there are plenty of problems to address.

**Comment by OwaisSiddiqui** [comment]
Okay, I see, thanks.
